package ddl

import (
	"testing"

	"github.com/bokwoon95/sq"
)

func Test_Column(t *testing.T) {
	type TT struct {
		dialect                 string
		item                    sq.SQLExcludeAppender
		excludedTableQualifiers []string
		wantQuery               string
		wantArgs                []interface{}
	}

	assert := func(t *testing.T, tt TT) {
		gotQuery, gotArgs, _, err := sq.ToSQLExclude(tt.dialect, tt.item, tt.excludedTableQualifiers)
		if err != nil {
			t.Fatal(testcallers(), err)
		}
		if diff := testdiff(gotQuery, tt.wantQuery); diff != "" {
			t.Error(testcallers(), diff)
		}
		if diff := testdiff(gotArgs, tt.wantArgs); diff != "" {
			t.Error(testcallers(), diff)
		}
	}

	t.Run("basic", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = Column{
			TableName:  "actor",
			ColumnName: "actor_id",
		}
		tt.wantQuery = "actor.actor_id"
		assert(t, tt)
	})

	t.Run("with table alias", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = Column{
			TableName:  "actor",
			TableAlias: "a",
			ColumnName: "actor_id",
		}
		tt.wantQuery = "a.actor_id"
		assert(t, tt)
	})

	t.Run("excludedTableQualifiers", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = Column{
			TableName:  "actor",
			ColumnName: "actor_id",
		}
		tt.excludedTableQualifiers = []string{"actor"}
		tt.wantQuery = "actor_id"
		assert(t, tt)
	})

	t.Run("quoted identifiers", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = Column{
			TableName:  "table with spaces",
			ColumnName: "column with spaces",
		}
		tt.excludedTableQualifiers = []string{"actor"}
		tt.wantQuery = `"table with spaces"."column with spaces"`
		assert(t, tt)
	})
}

func Test_AddColumnCommand(t *testing.T) {
	type TT struct {
		dialect   string
		item      Command
		wantQuery string
		wantArgs  []interface{}
	}

	assert := func(t *testing.T, tt TT) {
		gotQuery, gotArgs, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err != nil {
			t.Fatal(testcallers(), err)
		}
		if diff := testdiff(gotQuery, tt.wantQuery); diff != "" {
			t.Error(testcallers(), diff)
		}
		if diff := testdiff(gotArgs, tt.wantArgs); diff != "" {
			t.Error(testcallers(), diff)
		}
	}

	t.Run("(dialect == postgres) IDENTITY column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			AddIfNotExists: true,
			Column: Column{
				ColumnName:    "actor_id",
				ColumnType:    "INT",
				IsNotNull:     true,
				Identity:      BY_DEFAULT_AS_IDENTITY,
				CollationName: "C",
			},
		}
		tt.dialect = sq.DialectPostgres
		tt.wantQuery = `ADD COLUMN IF NOT EXISTS actor_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY COLLATE "C"`
		assert(t, tt)
	})

	t.Run("(dialect == postgres) GENERATED column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:          "full_name",
				ColumnType:          "TEXT",
				GeneratedExpr:       "first_name || ' ' || last_name",
				GeneratedExprStored: true,
			},
		}
		tt.dialect = sq.DialectPostgres
		tt.wantQuery = `ADD COLUMN full_name TEXT GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED`
		assert(t, tt)
	})

	t.Run("(dialect == postgres) AUTOINCREMENT column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "actor_id",
				ColumnType:    "INT",
				Autoincrement: true,
			},
		}
		tt.dialect = sq.DialectPostgres
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == postgres) GENERATED VIRTUAL column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "full_name",
				ColumnType:    "TEXT",
				GeneratedExpr: "first_name || ' ' || last_name",
			},
		}
		tt.dialect = sq.DialectPostgres
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect != postgres) add column if not exists", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			AddIfNotExists: true,
			Column: Column{
				ColumnName: "first_name",
				ColumnType: "TEXT",
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect != mysql) column with ON UPDATE CURRENT_TIMESTAMP", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:               "last_update",
				ColumnType:               "TIMESTAMPTZ",
				OnUpdateCurrentTimestamp: true,
			},
		}
		tt.dialect = sq.DialectPostgres
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) PRIMARY KEY column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:   "actor_id",
				ColumnType:   "INTEGER",
				IsPrimaryKey: true,
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) UNIQUE column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName: "actor_id",
				ColumnType: "INTEGER",
				IsUnique:   true,
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) NOT NULL column without a DEFAULT value", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName: "actor_id",
				ColumnType: "INTEGER",
				IsNotNull:  true,
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) NOT NULL column with an expression as DEFAULT value", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "actor_id",
				ColumnType:    "INTEGER",
				IsNotNull:     true,
				ColumnDefault: "(1 + 2 + 3)",
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) FOREIGN KEY column with non-null DEFAULT value", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "country_id",
				ColumnType:    "INT",
				ColumnDefault: "22",
			},
			ReferencesTable:  "country",
			ReferencesColumn: "country_id",
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) GENERATED STORED column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:          "full_name",
				ColumnType:          "TEXT",
				GeneratedExpr:       "first_name || ' ' || last_name",
				GeneratedExprStored: true,
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) IDENTITY column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName: "actor_id",
				ColumnType: "INT",
				Identity:   BY_DEFAULT_AS_IDENTITY,
			},
		}
		tt.dialect = sq.DialectSQLite
		_, _, _, err := sq.ToSQL(tt.dialect, tt.item)
		if err == nil {
			t.Fatal("expected error but got nil")
		}
	})

	t.Run("(dialect == sqlite) AUTOINCREMENT column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "actor_id",
				ColumnType:    "INT",
				Autoincrement: true,
			},
		}
		tt.dialect = sq.DialectSQLite
		tt.wantQuery = "ADD COLUMN actor_id INT AUTOINCREMENT"
		assert(t, tt)
	})

	t.Run("(dialect == sqlite) column with COLLATE", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "first_name",
				ColumnType:    "TEXT",
				CollationName: "nocase",
			},
		}
		tt.dialect = sq.DialectSQLite
		tt.wantQuery = "ADD COLUMN first_name TEXT COLLATE nocase"
		assert(t, tt)
	})

	t.Run("(dialect == sqlite) GENERATED VIRTUAL column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "full_name",
				ColumnType:    "TEXT",
				GeneratedExpr: "first_name || ' ' || last_name",
			},
		}
		tt.dialect = sq.DialectSQLite
		tt.wantQuery = "ADD COLUMN full_name TEXT GENERATED ALWAYS AS (first_name || ' ' || last_name) VIRTUAL"
		assert(t, tt)
	})

	t.Run("(dialect == mysql) AUTOINCREMENT column", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:    "actor_id",
				ColumnType:    "INT",
				Autoincrement: true,
			},
		}
		tt.dialect = sq.DialectMySQL
		tt.wantQuery = "ADD COLUMN actor_id INT AUTO_INCREMENT"
		assert(t, tt)
	})

	t.Run("(dialect == mysql) column with ON UPDATE CURRENT_TIMESTAMP", func(t *testing.T) {
		t.Parallel()
		var tt TT
		tt.item = &AddColumnCommand{
			Column: Column{
				ColumnName:               "last_update",
				ColumnType:               "DATETIME",
				ColumnDefault:            "CURRENT_TIMESTAMP",
				OnUpdateCurrentTimestamp: true,
			},
		}
		tt.dialect = sq.DialectMySQL
		tt.wantQuery = "ADD COLUMN last_update DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"
		assert(t, tt)
	})
}

// func Test_AlterColumnCommand(t *testing.T) {
// 	type TT struct {
// 		dialect   string
// 		item      Command
// 		wantQuery string
// 		wantArgs  []interface{}
// 	}
//
// 	assert := func(t *testing.T, tt TT) {
// 		gotQuery, gotArgs, _, err := sq.ToSQL(tt.dialect, tt.item)
// 		if err != nil {
// 			t.Fatal(testcallers(), err)
// 		}
// 		if diff := testdiff(gotQuery, tt.wantQuery); diff != "" {
// 			t.Error(testcallers(), diff)
// 		}
// 		if diff := testdiff(gotArgs, tt.wantArgs); diff != "" {
// 			t.Error(testcallers(), diff)
// 		}
// 	}
//
// 	t.Run("basic", func(t *testing.T) {
// 		t.Parallel()
// 		var tt TT
// 		tt.item = &AlterColumnCommand{}
// 		tt.wantQuery = "actor.actor_id"
// 		assert(t, tt)
// 	})
// }
//
// func Test_DropColumnCommand(t *testing.T) {
// 	type TT struct {
// 		dialect   string
// 		item      Command
// 		wantQuery string
// 		wantArgs  []interface{}
// 	}
//
// 	assert := func(t *testing.T, tt TT) {
// 		gotQuery, gotArgs, _, err := sq.ToSQL(tt.dialect, tt.item)
// 		if err != nil {
// 			t.Fatal(testcallers(), err)
// 		}
// 		if diff := testdiff(gotQuery, tt.wantQuery); diff != "" {
// 			t.Error(testcallers(), diff)
// 		}
// 		if diff := testdiff(gotArgs, tt.wantArgs); diff != "" {
// 			t.Error(testcallers(), diff)
// 		}
// 	}
//
// 	t.Run("basic", func(t *testing.T) {
// 		t.Parallel()
// 		var tt TT
// 		tt.item = &AddColumnCommand{}
// 		tt.wantQuery = "actor.actor_id"
// 		assert(t, tt)
// 	})
// }
//
// func Test_RenameColumnCommand(t *testing.T) {
// 	type TT struct {
// 		dialect   string
// 		item      Command
// 		wantQuery string
// 		wantArgs  []interface{}
// 	}
//
// 	assert := func(t *testing.T, tt TT) {
// 		gotQuery, gotArgs, _, err := sq.ToSQL(tt.dialect, tt.item)
// 		if err != nil {
// 			t.Fatal(testcallers(), err)
// 		}
// 		if diff := testdiff(gotQuery, tt.wantQuery); diff != "" {
// 			t.Error(testcallers(), diff)
// 		}
// 		if diff := testdiff(gotArgs, tt.wantArgs); diff != "" {
// 			t.Error(testcallers(), diff)
// 		}
// 	}
//
// 	t.Run("basic", func(t *testing.T) {
// 		t.Parallel()
// 		var tt TT
// 		tt.item = &AddColumnCommand{}
// 		tt.wantQuery = "actor.actor_id"
// 		assert(t, tt)
// 	})
// }
